# Generated by Django 3.0.4 on 2020-03-27 03:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_auto_20200327_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 27, 3, 0, 25, 124476, tzinfo=utc)),
        ),
    ]
