# Generated by Django 3.0.4 on 2020-03-27 03:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_auto_20200327_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.Users'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 27, 3, 24, 30, 487240, tzinfo=utc)),
        ),
    ]
